export const RESOURCE_TO_PRELOAD = [
  "images/pl_board.png",
  "images/pl_title.png",
  "images/pl_flicker.png",
  "images/logo.png",

  // {src: 'images/g_board.png', id: 'p13'},
  // {src: 'images/crystal.gif', id: 'p12'},
  // {src: 'images/indicator.jpg', id: 'p15'},
  // {src: 'images/input_box.png', id: 'p16'},
  // {src: 'images/input_btn.png', id: 'p18'},
  // {src: 'images/input_title.png', id: 'p19'},
  // {src: 'images/inputBG.jpg', id: 'p20'},

  // {src: 'images/light_board.png', id: 'p21'},
  // {src: 'images/logo.png', id: 'p22'},
  // {src: 'images/pink.gif', id: 'p23'},
  // {src: 'images/pl_up.png', id: 'p24'},
  // {src: 'images/ps_decorate.png', id: 'p25'},
  // {src: 'images/ps_heart.png', id: 'p26'},
  // {src: 'images/ps_title.png', id: 'p30'},
  // {src: 'images/ps_title_en.png', id: 'p31'},

  // {src: 'images/q1.png', id: 'p32'},
  // {src: 'images/q1_ap.png', id: 'p34'},
  // {src: 'images/q1_bp.png', id: 'p37'},

  // {src: 'images/q2.png', id: 'p38'},
  // {src: 'images/q3.png', id: 'p43'},
  // {src: 'images/q4.png', id: 'p50'},
  // {src: 'images/quiz2.png', id: 'p250'},
  // {src: 'images/quiz3.png', id: 'p264'},
  // {src: 'images/link_1.png', id: 'p251'},
  // {src: 'images/link_2.png', id: 'p252'},
  // {src: 'images/link_3.png', id: 'p253'},
  // {src: 'images/link_4.png', id: 'p254'},
  // {src: 'images/back_1.png', id: 'p255'},
  // {src: 'images/back_2.png', id: 'p256'},
  // {src: 'images/back_3.png', id: 'p257'},
  // {src: 'images/back_4.png', id: 'p258'},
  // {src: 'images/result_1.jpg', id: 'p259'},
  // {src: 'images/result_2.jpg', id: 'p260'},
  // {src: 'images/result_3.jpg', id: 'p261'},
  // {src: 'images/result_4.jpg', id: 'p262'},
  // {src: 'images/qrcode.png', id: 'p263'},

  // {src: 'images/q4_play.png', id: 'p54'},
  // {src: 'images/q4_pause.png', id: 'p55'},
  // {src: 'images/q5.png', id: 'p56'},

  // {src: 'images/quiz_board.png', id: 'p64'},
  // {src: 'images/x_quiz_board.png', id: 'p166'},
  // {src: 'images/x_light_board.png', id: 'p167'},
  // {src: 'images/red.gif', id: 'p65'},
  // {src: 'images/top1.png', id: 'p60'},
  // {src: 'images/top2.png', id: 'p61'},
  // {src: 'images/top3.png', id: 'p71'},
  // {src: 'images/top4.png', id: 'p72'},
  // {src: 'images/top5.png', id: 'p73'},
  // {src: 'images/wait.png', id: 'p74'},
  // {src: 'images/watch.gif', id: 'p75'},
];
